# Generated by Django 3.0.3 on 2020-08-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20200817_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='patients',
        ),
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(to='health.Patient'),
        ),
    ]
