# Generated by Django 3.0.3 on 2020-08-17 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_auto_20200817_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='patients',
        ),
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='health.Patient'),
        ),
        migrations.RemoveField(
            model_name='instance',
            name='doctors',
        ),
        migrations.AddField(
            model_name='instance',
            name='doctors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='health.Doctor'),
        ),
        migrations.RemoveField(
            model_name='instance',
            name='patients',
        ),
        migrations.AddField(
            model_name='instance',
            name='patients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='health.Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='health.Doctor'),
        ),
    ]
