# Generated by Django 3.0.3 on 2020-08-24 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_auto_20200824_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='health.Doctor'),
        ),
    ]
