# Generated by Django 3.0.3 on 2020-08-24 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_instance_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='health.Assigned_Doctor'),
        ),
    ]
