# Generated by Django 3.0.3 on 2020-08-24 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_auto_20200824_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='assigned_patient',
        ),
        migrations.AddField(
            model_name='doctor',
            name='assigned_patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='health.Patient'),
        ),
    ]
