# Generated by Django 3.0.3 on 2020-08-29 11:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_auto_20200829_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigned_Doctor',
            fields=[
                ('doctor_directory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='health.Doctor_Directory')),
                ('assigned_patient', models.ManyToManyField(default=None, help_text='who is/are the patients assigned to this doctor', to='health.Patient_Directory')),
            ],
            bases=('health.doctor_directory',),
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular case in the hospital', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('r', 'receiving treatment'), ('d', 'discharged'), ('a', 'admitted'), ('ar', 'admitted and receiving treatment')], default='r', help_text='patient status', max_length=3)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='health.Assigned_Doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='health.Patient_Directory')),
            ],
        ),
        migrations.CreateModel(
            name='Assigned_Patient',
            fields=[
                ('patient_directory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='health.Patient_Directory')),
                ('assigned_doctor', models.ManyToManyField(default=None, help_text='who is/are the patients assigned to this doctor', to='health.Doctor_Directory')),
            ],
            bases=('health.patient_directory',),
        ),
    ]
