# Generated by Django 3.0.3 on 2020-08-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_assigned_doctor_assigned_patient_instance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instance',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='instance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
