# Generated by Django 3.0.3 on 2020-08-31 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0012_auto_20200831_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='health.Assigned_Patient'),
        ),
    ]
