# Generated by Django 3.0.3 on 2020-09-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0014_auto_20200831_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instance',
            options={'ordering': ['date'], 'permissions': (('can_mark_admitted', 'Set patient as admitted'), ('can_mark_as_discharged', 'Set Patient as discharged'))},
        ),
    ]
